<?php
/**
 *  Copyright © Agile Codex Ltd. All rights reserved.
 *  License: https://www.agilecodex.com/license-agreement
 */
/**
 * @var \Acx\BrandSlider\Block\BrandSlider $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$htmlId = $block->getBrandSliderHtmlId();
$brandCollection = $block->getBrandCollection();
?>
<link rel="stylesheet" type="text/css"
      href="<?= $escaper->escapeUrl($block->getViewFileUrl('Acx_BrandSlider::css/slick.css')) ?>">
<div class="slick-list">
    <?php if ($block->getData("show_title")): ?>
        <h2><?= $escaper->escapeHtml($block->getTitle()) ?></h2>
    <?php endif; ?>
    <ul class="brand-list">
        <?php foreach ($brandCollection as $brand) : ?>
            <li data-thumb="<?= $escaper->escapeUrl($block->getBrandImageUrl($brand)) ?>">
                <img alt="<?= $escaper->escapeHtmlAttr($brand->getImageAlt()) ?>"
                     src="<?= $escaper->escapeUrl($block->getBrandImageUrl($brand)) ?>"/>
                <?php if ($brand->getName() && $block->getShowCaption()): ?>
                    <span><?= $escaper->escapeHtml($brand->getName()) ?></span>
                <?php endif; ?>
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<?php $scriptString = <<<script
    require([
        'jquery',
        'slick',
        'domReady!'
    ], function ($) {
        $('.brand-list').slick({
            dots: <?= (!$escaper->escapeJs($block->getDot())) ? "false" : "true" ?>,
            infinite: <?= (!$escaper->escapeJs($block->getInfinite())) ? "false" : "true" ?>,
            speed: <?= $escaper->escapeJs($block->getBrandsliderSpeed()) ?>,
            slidesToShow: <?= $block->getSlidesToShow() ? $escaper->escapeJs($block->getSlidesToShow()) : 5 ?>,
            slidesToScroll: <?= $block->getSlidesToScroll() ? $escaper->escapeJs($block->getSlidesToScroll()) : 2 ?>,
            responsive: [
                {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: <?= $block->getSlidesToShow() ? $escaper->escapeJs($block->getSlidesToShow()) : 4 ?>,
                        slidesToScroll: <?= $block->getSlidesToScroll() ? $escaper->escapeJs($block->getSlidesToScroll()) : 2 ?>,
                        infinite: <?= (!$block->getInfinite()) ? "false" : "true" ?>,
                        dots: <?= (!$block->getDot()) ? "false" : "true" ?>,
                    }
                },
                {
                    breakpoint: 600,
                    settings: {
                        slidesToShow: 3,
                        slidesToScroll: 3
                    }
                },
                {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 2,
                        slidesToScroll: 2
                    }
                }
            ]
        });
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
